error_exit – Physics of Liquids Monte-Carlo
error_exit Subroutine
5 statements
Source File
public subroutine error_exit(message)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: message
Called By
All Procedures
Abstract_add Abstract_add Abstract_add Abstract_add Abstract_allocate_coordinates Abstract_allocate_strings Abstract_allocate_strings Abstract_allocate_strings Abstract_are_outside_box Abstract_check_core Abstract_check_size Abstract_construct Abstract_construct Abstract_construct Abstract_construct Abstract_construct Abstract_construct Abstract_construct Abstract_construct Abstract_construct Abstract_construct Abstract_construct Abstract_construct Abstract_construct Abstract_construct Abstract_construct Abstract_construct Abstract_construct Abstract_construct Abstract_construct Abstract_construct Abstract_construct Abstract_construct Abstract_construct Abstract_construct Abstract_construct Abstract_construct Abstract_construct Abstract_construct Abstract_construct Abstract_construct Abstract_construct Abstract_construct Abstract_construct Abstract_construct Abstract_construct Abstract_construct Abstract_construct Abstract_construct Abstract_construct Abstract_construct Abstract_construct Abstract_construct_visitable_lists Abstract_decrease_delta Abstract_decrease_delta Abstract_destroy Abstract_destroy Abstract_destroy Abstract_destroy Abstract_destroy Abstract_destroy Abstract_destroy Abstract_destroy Abstract_destroy Abstract_destroy Abstract_destroy Abstract_destroy Abstract_destroy Abstract_destroy Abstract_destroy Abstract_destroy Abstract_destroy Abstract_destroy Abstract_destroy Abstract_destroy Abstract_destroy Abstract_destroy Abstract_destroy Abstract_destroy Abstract_destroy Abstract_destroy Abstract_destroy Abstract_destroy Abstract_destroy Abstract_destroy Abstract_destroy Abstract_destroy Abstract_destroy Abstract_destroy Abstract_destroy Abstract_destroy Abstract_destroy Abstract_destroy Abstract_destroy Abstract_destroy Abstract_destroy Abstract_destroy Abstract_destroy Abstract_destroy_visitable_lists Abstract_distance Abstract_fill_with_particles Abstract_get Abstract_get Abstract_get Abstract_get Abstract_get Abstract_get Abstract_get Abstract_get Abstract_get Abstract_get Abstract_get Abstract_get Abstract_get Abstract_get Abstract_get Abstract_get Abstract_get Abstract_get_delta Abstract_get_density Abstract_get_frequency_ratio Abstract_get_frequency_ratio Abstract_get_gap_centers Abstract_get_gap_radii Abstract_get_global_lbounds Abstract_get_global_ubounds Abstract_get_integer Abstract_get_inv_pow_activity Abstract_get_max_distance Abstract_get_max_distance Abstract_get_min_distance Abstract_get_minus Abstract_get_norm Abstract_get_num Abstract_get_num Abstract_get_num Abstract_get_num Abstract_get_num_choices Abstract_get_num_choices Abstract_get_num_choices Abstract_get_num_choices Abstract_get_numbers Abstract_get_plus Abstract_get_ratio Abstract_get_real_array Abstract_get_real_scalar Abstract_get_size Abstract_get_times_box_edge Abstract_get_width Abstract_increase_delta Abstract_increase_delta Abstract_index Abstract_is_boxed Abstract_is_dipolar Abstract_is_dipolar Abstract_is_dipolar Abstract_is_inside Abstract_is_inside Abstract_is_sparse_in_z Abstract_meet Abstract_meet Abstract_meet Abstract_metropolis_algorithm Abstract_metropolis_algorithm Abstract_metropolis_algorithm Abstract_position_from_ceiling Abstract_position_from_floor Abstract_read Abstract_remove Abstract_remove Abstract_remove Abstract_remove Abstract_reset Abstract_reset Abstract_reset Abstract_reset Abstract_reset Abstract_reset Abstract_reset Abstract_reset Abstract_reset Abstract_reset_selectors Abstract_reset_selectors Abstract_reset_selectors Abstract_resize_only Abstract_restore Abstract_save Abstract_save Abstract_set Abstract_set Abstract_set Abstract_set Abstract_set Abstract_set Abstract_set Abstract_set Abstract_set Abstract_set Abstract_set Abstract_set Abstract_set_all Abstract_set_core Abstract_set_delta_energy Abstract_set_min_distance Abstract_set_neighbours Abstract_skip Abstract_target Abstract_target Abstract_target Abstract_target Abstract_target Abstract_target Abstract_target Abstract_target Abstract_target Abstract_target Abstract_target_real Abstract_translate Abstract_try Abstract_try Abstract_try Abstract_try Abstract_try Abstract_try Abstract_try Abstract_try Abstract_tune Abstract_update_add Abstract_update_add Abstract_update_exchange Abstract_update_exchange Abstract_update_remove Abstract_update_remove Abstract_update_rotation Abstract_update_rotation Abstract_update_switch Abstract_update_switch Abstract_update_translation Abstract_update_translation Abstract_update_transmutation Abstract_update_transmutation Abstract_vector Abstract_visit Abstract_visit Abstract_visit Abstract_visit Abstract_visit Abstract_visit Abstract_visit_add Abstract_visit_add Abstract_visit_add Abstract_visit_contacts Abstract_visit_contacts Abstract_visit_dipolar Abstract_visit_dipolar_neighbours Abstract_visit_dipolar_neighbours Abstract_visit_energy Abstract_visit_energy Abstract_visit_exchange Abstract_visit_exchange Abstract_visit_field Abstract_visit_inter Abstract_visit_intra Abstract_visit_min_distance Abstract_visit_min_distance Abstract_visit_remove Abstract_visit_remove Abstract_visit_remove Abstract_visit_rotation Abstract_visit_rotation Abstract_visit_rotation Abstract_visit_short Abstract_visit_switch Abstract_visit_switch Abstract_visit_translation Abstract_visit_translation Abstract_visit_transmutation Abstract_visit_transmutation Abstract_visit_walls Abstract_write Abstract_write Abstract_write Abstract_write Abstract_write Abstract_write Abstract_write_array Abstract_write_integers Abstract_write_reals Abstract_write_scalar Add_acceptation_probability Add_define_exchange add_double add_energies Add_increment_hit Add_increment_success add_single add_to_report add_to_report Add_update_component Add_visit_dipolar Add_visit_field Add_visit_short Add_visit_walls allocate allocate allocate allocate allocate allocate allocate_coordinates allocate_element allocate_field_expression allocate_floor_penetration allocate_triangle allocate_xy allocate_xyz apply_external_field apply_external_field_from apply_external_field_from_json Array_add Array_construct Array_destroy Array_remove Array_set Array_visit_contacts Array_visit_dipolar_neighbours Array_visit_energy Array_visit_min_distance Arrays_restore Arrays_save average Block_get_height Block_meet Block_set box_size_can_change box_size_can_change_from_changed box_size_change_reset_cells Boxed_construct Boxed_destroy Boxed_get_origin Boxed_get_size calculate_ratio change_counter_reset change_counters_reset change_success_set change_successes_set changes_counter_reset changes_success_set check check_array_size check_consistency check_data_found check_file_exists check_in_range check_increase_factor check_integer_array_size check_norm check_periodicity_xy check_positive check_positive_integer_array check_positive_integer_scalar check_positive_real_array check_positive_real_scalar check_potential_domain check_ratio check_real_array_size check_string_not_empty Chemical_Potential_construct Chemical_Potential_destroy Chemical_Potential_set clone_real component_can_exchange component_can_exchange_from_chemical_potential component_can_rotate component_can_translate component_exists component_exists_from_num component_has_orientations component_has_positions component_interacts_with_wall component_is_dipolar component_is_dipolar_from_dipole_moments component_is_dipolar_from_json components_interact components_interact_from_min_distance components_interact_from_pair_potential Concrete_acceptation_probability Concrete_acceptation_probability Concrete_acceptation_probability Concrete_acceptation_probability Concrete_construct Concrete_construct Concrete_construct Concrete_construct Concrete_construct Concrete_construct Concrete_construct Concrete_construct Concrete_decrease_delta Concrete_decrease_delta Concrete_define_swap Concrete_define_teleportation Concrete_destroy Concrete_destroy Concrete_destroy Concrete_destroy Concrete_destroy Concrete_destroy Concrete_destroy Concrete_destroy Concrete_get Concrete_get Concrete_get Concrete_get Concrete_get_num_choices Concrete_get_num_choices Concrete_get_num_choices Concrete_get_num_choices Concrete_increase_delta Concrete_increase_delta Concrete_metropolis_algorithm Concrete_metropolis_algorithm Concrete_metropolis_algorithm Concrete_metropolis_algorithm Concrete_reset_selectors Concrete_reset_selectors Concrete_reset_selectors Concrete_reset_selectors Concrete_try Concrete_try Concrete_try Concrete_try Concrete_update_components Concrete_update_components Concrete_visit_dipolar Concrete_visit_dipolar Concrete_visit_fields Concrete_visit_fields Concrete_visit_short Concrete_visit_short Concrete_visit_walls Concrete_visit_walls Constant_construct Constant_destroy Constant_get Constant_set Constant_set construct construct construct construct construct_element Coordinates_construct Coordinates_destroy Coordinates_read create create create create create create create create create create create create create create create create create create create create create create create create create create create create create create create create create create create create create create create create create create create create create create create create create create create create create create create create create create create create create create create create create create create create create create create create create create create create create create create create create create create create create create_accessible_domains_size create_add create_all create_boxes_size create_boxes_size_change create_boxes_size_exchange create_change_counters create_changes_counters create_changes_successes create_components create_coordinates_from_file create_dipolar_energies create_element create_element create_element create_element create_element create_element create_element create_element create_element create_element create_element create_exploring create_exploring create_field_energies create_filename_from_argument create_from_boxes create_from_json create_from_json create_from_value create_from_walls create_full create_full_element create_full_line create_generating create_generating create_half create_half_element create_half_line create_line create_line create_line create_line create_line create_line create_line create_line create_orientation create_orientations create_position create_positions create_positions_from_file create_random_orientation create_random_positions create_rectangle create_rectangle create_rectangle create_rectangle_counters create_remove create_rotated_orientations create_rotation create_rotation create_short_energies create_square_counters create_swaps_counters create_swaps_successes create_switch create_switches_successes create_teleportations_counters create_teleportations_successes create_translated_positions create_translation create_translation create_transmutation create_transmutations_successes create_triangle create_triangle create_triangle create_triangle_counters create_volumes_change_success create_volumes_exchange_success create_walls_energies deallocate deallocate deallocate_list des_real_B des_real_C destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy_all destroy_all destroy_change_counters destroy_changes_counters destroy_changes_successes destroy_components destroy_element destroy_element destroy_element destroy_element destroy_element destroy_element destroy_element destroy_element destroy_element destroy_element destroy_element destroy_element destroy_element destroy_element destroy_element destroy_element destroy_element destroy_element destroy_exploring destroy_generating destroy_line destroy_line destroy_line destroy_line destroy_line destroy_line destroy_line destroy_line destroy_line destroy_line destroy_line destroy_line destroy_line destroy_line destroy_line destroy_line destroy_number_line destroy_number_triangle destroy_rectangle destroy_rectangle destroy_rectangle destroy_rectangle destroy_rectangle_counters destroy_rectangles destroy_static destroy_swaps_counters destroy_teleportations_counters destroy_teleportations_successes destroy_triangle destroy_triangle destroy_triangle destroy_triangle_counters diff_triangle dipolar_energy_is_negative domains_overlap Dot_construct Dot_destroy Dot_write edge Equipartition_construct Equipartition_destroy Equipartition_set error_exit Exploring_check Exploring_construct Exploring_destroy Flat_get_height Flat_meet Forgetful_construct Forgetful_destroy Forgetful_get Forgetful_save Full_construct Gaussian_get Gaussian_get_width Gaussian_set Generating_check Generating_construct Generating_destroy Half_construct i_component i_component_from_json i_exclude_particle ij_components ij_components_from_json increase_coordinates_size increase_nodes_size increment_line increment_triangle Inter_construct Inter_read_and_fill Intra_construct Intra_read_and_fill is_inside_excluded is_inside_included list_is_array list_is_linked_list Lists_restore Lists_save LJ_get LJ_set logical_from_json make_dipoles_graph make_dipoles_graph_from_json make_dipoles_graph_from_visitor markov_orientation max_distance measure_chemical_potentials measure_chemical_potentials_from_json measure_chemical_potentials_from_method measure_pressure measure_pressure_from_json measure_pressure_from_method metropolis_algorithm mixture_can_exchange mixture_can_exchange_from_json normal_random_number normal_random_number_scalar normal_random_number_vector Null_add Null_add Null_add Null_add Null_are_neighbour Null_are_outside_box Null_check_nums Null_clone Null_construct Null_construct Null_construct Null_construct Null_construct Null_construct Null_construct Null_construct Null_construct Null_construct Null_construct Null_construct Null_construct Null_construct Null_construct Null_construct Null_construct Null_construct Null_construct Null_construct Null_construct Null_construct Null_construct Null_construct Null_construct Null_construct Null_construct Null_construct Null_construct Null_construct Null_construct Null_construct Null_construct Null_construct Null_construct Null_construct Null_construct Null_construct Null_construct Null_construct Null_copy Null_decrease_delta Null_decrease_delta Null_decrease_delta Null_destroy Null_destroy Null_destroy Null_destroy Null_destroy Null_destroy Null_destroy Null_destroy Null_destroy Null_destroy Null_destroy Null_destroy Null_destroy Null_destroy Null_destroy Null_destroy Null_destroy Null_destroy Null_destroy Null_destroy Null_destroy Null_destroy Null_destroy Null_destroy Null_destroy Null_destroy Null_destroy Null_destroy Null_destroy Null_destroy Null_destroy Null_destroy Null_destroy Null_destroy Null_destroy Null_destroy Null_destroy Null_destroy Null_destroy Null_destroy Null_destroy Null_destroy Null_destroy Null_destroy Null_destroy Null_destroy Null_destroy Null_destroy Null_destroy Null_expression Null_get Null_get Null_get Null_get Null_get Null_get Null_get Null_get Null_get Null_get Null_get Null_get Null_get Null_get Null_get Null_get Null_get Null_get Null_get Null_get Null_get Null_get Null_get Null_get_delta Null_get_delta Null_get_density Null_get_distance Null_get_frequency_ratio Null_get_frequency_ratio Null_get_gap Null_get_global_bounds Null_get_height Null_get_integer Null_get_inv_pow_activity Null_get_max_distance Null_get_norm Null_get_num Null_get_num Null_get_num Null_get_num Null_get_num_choices Null_get_num_choices Null_get_numbers Null_get_origin Null_get_ratio Null_get_ratios Null_get_real_array Null_get_real_scalar Null_get_size Null_get_times_box_edge Null_get_width Null_get_width Null_increase_delta Null_increase_delta Null_increase_delta Null_index Null_is_boxed Null_is_dipolar Null_is_dipolar Null_is_dipolar Null_is_inside Null_is_inside Null_is_sparse_in_z Null_meet Null_meet Null_meet Null_meet Null_meet_contact Null_meet_min_distance Null_read Null_remove Null_remove Null_remove Null_remove Null_rescale_all Null_reset Null_reset Null_reset Null_reset Null_reset Null_reset Null_reset Null_reset Null_reset Null_reset Null_reset Null_reset_selectors Null_resize_only Null_restore Null_save Null_save Null_set Null_set Null_set Null_set Null_set Null_set Null_set Null_set Null_set Null_set Null_set Null_set Null_set Null_set_all Null_set_min_distance Null_set_real_pair_flag Null_set_skip_layers Null_skip Null_target Null_target Null_target Null_target Null_target Null_target Null_target Null_target Null_target Null_target Null_target Null_translate Null_try Null_try Null_try Null_try Null_try Null_try Null_tune Null_update_exchange Null_update_exchange Null_update_switch Null_update_switch Null_update_translation Null_update_translation Null_update_transmutation Null_update_transmutation Null_visit Null_visit Null_visit Null_visit Null_visit Null_visit Null_visit Null_visit Null_visit_contacts Null_visit_contacts Null_visit_dipolar_neighbours Null_visit_dipolar_neighbours Null_visit_energy Null_visit_energy Null_visit_exchange Null_visit_exchange Null_visit_exchange Null_visit_inter Null_visit_intra Null_visit_min_distance Null_visit_min_distance Null_visit_switch Null_visit_switch Null_visit_translation Null_visit_translation Null_visit_transmutation Null_visit_transmutation Null_visit_transmutation Null_write Null_write Null_write Null_write Null_write Null_write Null_write_array Null_write_integers Null_write_reals Null_write_scalar num_boxes num_boxes_from_json num_components num_components_from_json observables_create_exploring observables_create_generating observables_destroy_exploring observables_destroy_generating Orientations_construct Orientations_construct Orientations_destroy Orientations_destroy Orientations_read Orientations_rescale_all Orientations_set Parallelepiped_construct Parallelepiped_destroy Parallelepiped_get_origin Parallelepiped_get_size pbc_3d_index periodicity_is_xy periodicity_is_xyz Plain_construct Plain_destroy Plain_fill Plain_write plate_expression Plates_get Plates_set plmc_catch_density_help plmc_catch_exploring_help plmc_catch_generating_help plmc_catch_help_core plmc_catch_radial_help plmc_reset plmc_set_num_snaps plmc_set_num_steps plmc_visit plmc_write point_is_inside_box Positions_construct Positions_construct Positions_destroy Positions_destroy Positions_read Positions_rescale_all Positions_set Random_construct Random_copy Random_destroy random_integer Raw_construct Raw_construct Raw_destroy Raw_destroy Raw_expression Raw_meet Raw_reset Raw_set_domain Raw_set_domain read read_box_size read_complete_coordinates read_coordinates reci_number_1_sym reci_number_2_sym Rectangular_get Rectangular_get_width Rectangular_set Rectangular_visit Rectangular_visit_exchange Rectangular_visit_transmutation Remove_acceptation_probability Remove_define_exchange Remove_increment_hit Remove_increment_success Remove_update_component Remove_visit_dipolar Remove_visit_field Remove_visit_short Remove_visit_walls reset reset reset reset_box_particle reset_box_particles_swap reset_box_volume_change reset_boxes_particles_swap reset_boxes_volume_exchange reset_counters reset_neighbour_cells reset_real reset_visitable_cells restore Rotation_define_move Rotation_increment_hit Rotation_increment_success Rotation_update_component Rotation_visit_dipolar Rotation_visit_field Rotation_visit_short Rotation_visit_walls save Scalable_clone Scalable_construct Scalable_destroy Scalable_reset Scalable_set_real_pair_flag Scalable_target Scalable_visit set set set set set_are_dipolar set_bounds set_can_exchange set_can_rotate set_can_translate set_density_type set_energies set_energies_triangle set_exist set_exp_kz set_field_expression set_floor_penetration set_fourier set_from_corner set_from_json set_from_seed set_from_snap set_from_urandom set_from_wall set_have_orientations set_have_positions set_increase_factor set_nums_particles set_selector set_successes set_tuner_parameters set_tuning_parameters sphere_surface Spherical_visit Spherical_visit_exchange Spherical_visit_transmutation standard_deviation sum_line Switch_acceptation_probability Switch_define_swap Switch_increment_hit Switch_increment_success Switch_update_components Switch_visit_dipolar Switch_visit_field Switch_visit_short Switch_visit_walls Tabulated_construct Tabulated_construct Tabulated_create_tabulation Tabulated_destroy Tabulated_destroy Tabulated_expression Tabulated_meet Tabulated_reset Tabulated_set_domain Tabulated_set_domain Tabulated_set_tabulation total_volume_can_change total_volume_can_change_from_beta_pressure total_volume_can_change_from_json Translation_define_move Translation_increment_hit Translation_increment_success Translation_update_component Translation_visit_dipolar Translation_visit_field Translation_visit_short Translation_visit_walls Transmutation_acceptation_probability Transmutation_define_swap Transmutation_increment_hit Transmutation_increment_success Transmutation_update_components Transmutation_visit_dipolar transmutation_visit_dipolar Transmutation_visit_field transmutation_visit_field Transmutation_visit_short transmutation_visit_short Transmutation_visit_walls transmutation_visit_walls triangle_observables_add triangle_observables_diff triangle_observables_init triangle_observables_sum Unscalable_clone Unscalable_construct Unscalable_destroy Unscalable_reset Unscalable_set_real_pair_flag Unscalable_target Unscalable_visit update update_add update_remove use_domain use_permittivity use_permittivity_from use_permittivity_from_json use_reciprocal_lattice use_reciprocal_lattice_from use_reciprocal_lattice_from_json use_walls use_walls_from_floor_penetration use_walls_from_json use_walls_from_walls visit visit visit visit_add visit_add visit_add_dipolar visit_add_short visit_all visit_cells_contacts visit_cells_energies visit_cells_min_distance visit_component visit_des_real visit_des_self visit_different visit_dipolar visit_dipolar visit_dipolar_neighbours visit_exchange visit_field visit_lower visit_remove visit_remove visit_remove_dipolar visit_remove_short visit_rotation visit_short visit_short visit_short_inter visit_short_intra visit_translation visit_walls Walled_construct Walled_destroy Walled_get_origin Walled_get_size warning_continue write_coordinates write_coordinates_from_json write_energies write_exploring_observables write_generating_observables XY_check XY_check_nums XY_folded XY_get XY_get XY_get_delta XY_get_ratios XY_meet_contact XY_meet_min_distance XY_set_skip_layers XYZ_check XYZ_check_nums XYZ_folded XYZ_get XYZ_get XYZ_get_delta XYZ_get_ratios XYZ_meet_contact XYZ_meet_min_distance XYZ_set_skip_layers XZ_construct XZ_destroy XZ_fill XZ_write Yukawa_get Yukawa_set Z_construct Z_destroy Z_fill Z_write
Call graph
construct calls error_exit, check_data_found
create_swaps_successes calls error_exit
create_from_walls calls error_exit
allocate calls error_exit, check_data_found
create_from_boxes calls error_exit
create calls error_exit, apply_external_field, total_volume_can_change, use_walls, check, check_data_found, set_are_dipolar, make_dipoles_graph, measure_chemical_potentials, construct, set_density_type, create_swaps_successes, create_random_positions, create_random_orientation, create_filename_from_argument, allocate_field_expression, set_field_expression, use_permittivity, use_reciprocal_lattice, measure_pressure, create_teleportations_successes, create_field_energies, component_is_dipolar, check_consistency, create_line, create_all, create_element, create_rotated_orientations, create_translated_positions, allocate_floor_penetration, set_floor_penetration, set, create_rectangle
create_random_positions calls error_exit
inter_construct calls error_exit, check_in_range
create_filename_from_argument calls error_exit, check_file_exists, check_positive
allocate_field_expression calls error_exit, check_data_found
create_transmutation calls error_exit
abstract_set calls error_exit, check_array_size, check_positive, check_increase_factor
create_switch calls error_exit
xz_fill calls error_exit
set_field_expression calls error_exit, check_data_found
plmc_set_num_snaps calls error_exit, write_coordinates
check_string_not_empty calls error_exit
check_data_found calls error_exit
create_remove calls error_exit
create_positions calls error_exit
create_orientations calls error_exit
create_random_orientation calls error_exit
create_position calls error_exit
abstract_try calls error_exit, random_integer
create_add calls error_exit
create_rotated_orientations calls error_exit, check_data_found
abstract_set_all calls error_exit
abstract_reset calls error_exit, check_positive
allocate_floor_penetration calls error_exit, check_data_found, use_walls
check_potential_domain calls error_exit, check_positive
set_floor_penetration calls error_exit, check_data_found
create_orientation calls error_exit
check_in_range calls error_exit
create_translated_positions calls error_exit, check_data_found
set calls error_exit, check_data_found, set_from_urandom, set_from_seed, set_from_snap, set_from_json
set_from_urandom calls error_exit
create_line calls error_exit, set_are_dipolar, create
check_integer_array_size calls error_exit
check_ratio calls error_exit
check_real_array_size calls error_exit
z_fill calls error_exit
check_positive_integer_scalar calls error_exit
plain_fill calls error_exit
check_increase_factor calls error_exit, check_positive
tabulated_reset calls error_exit
check_file_exists calls error_exit
block_set calls error_exit, check_array_size, check_positive
create_from_json calls error_exit, check_data_found, use_walls
raw_reset calls error_exit
create_coordinates_from_file calls error_exit, check_file_exists
create_teleportations_successes calls error_exit
visit calls error_exit
create_rotation calls error_exit
create_element calls error_exit, construct, construct_element
construct_element calls error_exit
abstract_add calls error_exit, check_array_size
create_translation calls error_exit
abstract_read calls error_exit, check_file_exists
check_positive_real_scalar calls error_exit
plmc_catch_help_core calls error_exit
abstract_check_size calls error_exit
exploring_check calls error_exit
abstract_check_core calls error_exit
xy_check_nums calls error_exit
abstract_construct calls error_exit, check_positive, check_string_not_empty, check_array_size, check_ratio, check_increase_factor
xyz_check_nums calls error_exit
radial calls create_filename_from_argument, plmc_set_num_snaps, plmc_catch_radial_help
set_from_snap calls create_filename_from_argument
density calls create_filename_from_argument, plmc_set_num_snaps, check_in_range, use_walls, plmc_catch_density_help
abstract_set_core calls check_string_not_empty, check_positive
dot_construct calls check_string_not_empty
z_construct calls check_string_not_empty, check_positive
xz_construct calls check_string_not_empty, check_positive
set_density_type calls check_data_found
logical_from_json calls check_data_found
set_tuner_parameters calls check_data_found
num_boxes_from_json calls check_data_found
num_components_from_json calls check_data_found
i_component_from_json calls check_data_found
set_from_json calls check_data_found
ij_components_from_json calls check_data_found, check_array_size
plmc_set_num_steps calls check_data_found, check_positive
set_tuning_parameters calls check_data_found
make_dipoles_graph_from_json calls logical_from_json
write_coordinates_from_json calls logical_from_json
apply_external_field_from_json calls logical_from_json
mixture_can_exchange_from_json calls logical_from_json
component_is_dipolar_from_json calls logical_from_json
total_volume_can_change_from_json calls logical_from_json
use_walls_from_json calls logical_from_json
plmc_explore calls logical_from_json, measure_pressure, measure_chemical_potentials, plmc_visit, plmc_catch_exploring_help
use_permittivity_from_json calls logical_from_json
use_reciprocal_lattice_from_json calls logical_from_json
measure_pressure_from_json calls logical_from_json
measure_chemical_potentials_from_json calls logical_from_json
make_dipoles_graph calls make_dipoles_graph_from_json
write_coordinates calls write_coordinates_from_json
apply_external_field calls apply_external_field_from_json
create_field_energies calls apply_external_field, component_is_dipolar
mixture_can_exchange calls mixture_can_exchange_from_json
component_is_dipolar calls component_is_dipolar_from_json
set_are_dipolar calls component_is_dipolar
total_volume_can_change calls total_volume_can_change_from_json
use_walls calls use_walls_from_json
check calls use_walls
use_permittivity calls use_permittivity_from_json
check_consistency calls use_permittivity, use_reciprocal_lattice
use_reciprocal_lattice calls use_reciprocal_lattice_from_json
measure_pressure calls measure_pressure_from_json
measure_chemical_potentials calls measure_chemical_potentials_from_json
create_all calls set_tuner_parameters, set_tuning_parameters, create
num_boxes calls num_boxes_from_json
num_components calls num_components_from_json
i_component calls i_component_from_json
ij_components calls ij_components_from_json
raw_set_domain calls check_potential_domain
tabulated_set_domain calls check_potential_domain
orientations_set calls check_in_range, check_array_size, check_positive
abstract_remove calls check_in_range, check_array_size
positions_set calls check_in_range, check_array_size
intra_construct calls check_in_range
check_array_size calls check_integer_array_size, check_real_array_size
concrete_construct calls check_increase_factor, check_array_size, check_positive
parallelepiped_construct calls check_array_size, check_positive
constant_set calls check_array_size
markov_orientation calls check_array_size
set_from_seed calls check_array_size
concrete_get calls markov_orientation
check_positive_integer_array calls check_positive_integer_scalar
check_positive calls check_positive_integer_scalar, check_positive_real_scalar, check_positive_integer_array, check_positive_real_array
gaussian_set calls check_positive
rectangular_set calls check_positive
plates_set calls check_positive
random_integer calls check_positive
half_construct calls check_positive
full_construct calls check_positive
lj_set calls check_positive
yukawa_set calls check_positive
positions_rescale_all calls check_positive
concrete_try calls random_integer
translation_define_move calls random_integer
remove_define_exchange calls random_integer
transmutation_define_swap calls random_integer
concrete_define_teleportation calls random_integer
rotation_define_move calls random_integer
switch_define_swap calls random_integer
concrete_define_swap calls random_integer
read_box_size calls check_file_exists
read_complete_coordinates calls check_file_exists
read calls read_box_size, read_complete_coordinates
create_positions_from_file calls create_coordinates_from_file
plmc_visit calls visit
plmc_generate calls plmc_visit, plmc_catch_generating_help
create_triangle calls create_element
create_rectangle calls create
check_positive_real_array calls check_positive_real_scalar
plmc_catch_generating_help calls plmc_catch_help_core
plmc_catch_density_help calls plmc_catch_help_core
plmc_catch_exploring_help calls plmc_catch_help_core
plmc_catch_radial_help calls plmc_catch_help_core