density – Physics of Liquids Monte-Carlo
density Program
76 statements
Source File
Uses:
iso_fortran_env
data_constants
data_input_prefixes
data_arguments
json_module
procedures_json_data_factory
procedures_checks
procedures_command_arguments
classes_periodic_box
procedures_boxes_factory
classes_floor_penetration
classes_visitable_walls
procedures_walls_factory
procedures_environment_inquirers
classes_min_distance
procedures_hard_core_factory
types_raw_coordinates
procedures_mixture_inquirers
types_component_coordinates_reader_selector
procedures_complete_coordinates_reader
procedures_plmc_iterations
classes_density_explorer
procedures_density_explorer_factory
procedures_plmc_help
Calls
Variables
periodic_boxes max_box_size box_size visitable_walls floor_penetration wall_min_distance num_components i_component selector num_snaps i_snap density_explorer snap_filename raw_coordinates generating_data exploring_data
Variables
Type Attributes Name Initial
class(Abstract_Periodic_Box), allocatable :: periodic_boxes(:)
real(kind=DP), dimension(num_dimensions) :: max_box_size
real(kind=DP), dimension(num_dimensions) :: box_size
class(Abstract_Visitable_Walls), allocatable :: visitable_walls(:)
class(Abstract_Floor_Penetration), allocatable :: floor_penetration
class(Abstract_Min_Distance), allocatable :: wall_min_distance
integer :: num_components
integer :: i_component
type(Component_Coordinates_Reader_Selector) :: selector
integer :: num_snaps
integer :: i_snap
class(Abstract_Density_Explorer), allocatable :: density_explorer
character(len=:), allocatable :: snap_filename
type(Concrete_Raw_Coordinates) :: raw_coordinates
type(json_file) :: generating_data
type(json_file) :: exploring_data
All Programs
density plmc_explore plmc_generate radial
Call graph
density calls use_walls, complete_coordinates_read, property_i_component, boxes_create, plmc_set_num_snaps, density_explorer_create, complete_coordinates_deallocate, json_data_destroy, plmc_catch_density_help, check_in_range, density_explorer_destroy, property_num_components, walls_destroy, boxes_destroy, walls_create, hard_core_destroy, json_data_create, hard_core_create, create_filename_from_argument
use_walls calls use_walls_from_json, use_walls_from_walls, use_walls_from_floor_penetration
plmc_set_num_snaps calls error_exit, write_coordinates
plmc_catch_density_help calls plmc_catch_help_core
check_in_range calls error_exit
create_filename_from_argument calls error_exit, check_positive, check_file_exists
use_walls_from_json calls logical_from_json
logical_from_json calls check_data_found
check_data_found calls error_exit
write_coordinates calls write_coordinates_from_json
write_coordinates_from_json calls logical_from_json
plmc_catch_help_core calls error_exit
check_positive calls check_positive_integer_array, check_positive_real_scalar, check_positive_real_array, check_positive_integer_scalar
check_file_exists calls error_exit
check_positive_integer_array calls check_positive_integer_scalar
check_positive_real_scalar calls error_exit, warning_continue
check_positive_real_array calls check_positive_real_scalar
check_positive_integer_scalar calls error_exit, warning_continue