plmc_generate – Physics of Liquids Monte-Carlo
plmc_generate Program
74 statements
Source File
Uses:
iso_fortran_env
data_output_objects
data_arguments
json_module
procedures_json_data_factory
procedures_json_reports_factory
procedures_random_seed_factory
types_physical_model_wrapper
procedures_generating_algorithms_factory
types_markov_chain_generator_wrapper
types_generating_observables_wrapper
types_generating_io
procedures_plmc_factory
procedures_plmc_resetter
procedures_plmc_visitor
procedures_plmc_writer
procedures_plmc_help
Calls
Variables
physical_model markov_chain_generator observables json io num_tuning_steps num_steps i_step changes_tuned
Variables
Type Attributes Name Initial
type(Physical_Model_Wrapper) :: physical_model
type(Markov_Chain_Generator_Wrapper) :: markov_chain_generator
type(Generating_Observables_Wrapper) :: observables
type(json_core) :: json
type(Generating_IO_Wrapper) :: io
integer :: num_tuning_steps
integer :: num_steps
integer :: i_step
logical :: changes_tuned
All Programs
density plmc_explore plmc_generate radial
Call graph
plmc_generate calls plmc_create, plmc_set, generating_algorithms_add_to_report, json_data_destroy, plmc_reset, json_reports_create, plmc_visit, plmc_destroy, random_seed_add_to_report, plmc_catch_generating_help, plmc_write, json_reports_destroy, json_data_create
plmc_reset calls dipolar_interactions_reset, short_interactions_reset
plmc_visit calls visit
plmc_catch_generating_help calls plmc_catch_help_core
plmc_write calls write_exploring_observables, write_generating_observables
visit calls short_interactions_visit, cells, walls_visitors, dipolar_interactions_visit, error_exit, dipolar_interactions_dynamic, components_visitors
plmc_catch_help_core calls error_exit
write_exploring_observables calls beta_pressures_excess, insertion_successes, adjacency_matrices, write_energies, inv_pow_activities, maximum_boxes_compression_delta
write_generating_observables calls write_energies, changes, accessible_domains_size