plmc_explore – Physics of Liquids Monte-Carlo
plmc_explore Program
76 statements
Source File
Uses:
iso_fortran_env
data_output_objects
data_arguments
json_module
procedures_json_data_factory
procedures_json_reports_factory
procedures_property_inquirers
procedures_random_seed_factory
types_physical_model_wrapper
procedures_exploration_inquirers
types_markov_chain_explorer_wrapper
procedures_markov_chain_explorer_factory
types_exploring_observables_wrapper
types_exploring_io
procedures_plmc_factory
procedures_plmc_resetter
procedures_plmc_visitor
procedures_plmc_writer
procedures_plmc_help
Note
While plmc_generate accepts an arbitrary number of boxes, plmc_explore overrides it to 1. Hence each box can be explored separately.
Bug
create must be in [[procedures_plmc_factory:plmc_create]] but it doesn't work. Is it an ifort bug?
Calls
Variables
physical_model markov_chain_explorer observables json generating_parameters io i_box num_snaps i_snap visit_energies skip_dipolar_interactions_reset
Variables
Type Attributes Name Initial
type(Physical_Model_Wrapper) :: physical_model
type(Markov_Chain_Explorer_Wrapper) :: markov_chain_explorer
type(Exploring_Observables_Wrapper) :: observables
type(json_core) :: json
type(json_file) :: generating_parameters
type(Exploring_IO_Wrapper) :: io
integer :: i_box
integer :: num_snaps
integer :: i_snap
logical :: visit_energies
logical :: skip_dipolar_interactions_reset
All Programs
density plmc_explore plmc_generate radial
Call graph
plmc_explore calls plmc_create, plmc_set, plmc_catch_exploring_help, markov_chain_explorer_create, measure_pressure, json_data_destroy, measure_chemical_potentials, set, logical_from_json, json_reports_create, plmc_reset, plmc_visit, random_seed_add_to_report, plmc_destroy, try, plmc_write, json_reports_destroy, json_data_create, markov_chain_explorer_destroy
plmc_catch_exploring_help calls plmc_catch_help_core
measure_pressure calls measure_pressure_from_json, measure_pressure_from_method
measure_chemical_potentials calls measure_chemical_potentials_from_json, measure_chemical_potentials_from_method
logical_from_json calls check_data_found
plmc_reset calls dipolar_interactions_reset, short_interactions_reset
plmc_visit calls visit
plmc_write calls write_exploring_observables, write_generating_observables
plmc_catch_help_core calls error_exit
measure_pressure_from_json calls logical_from_json
measure_chemical_potentials_from_json calls logical_from_json
check_data_found calls error_exit
visit calls error_exit, short_interactions_visit, cells, walls_visitors, dipolar_interactions_visit, dipolar_interactions_dynamic, components_visitors
write_exploring_observables calls beta_pressures_excess, insertion_successes, adjacency_matrices, write_energies, inv_pow_activities, maximum_boxes_compression_delta
write_generating_observables calls write_energies, changes, accessible_domains_size