radial – Physics of Liquids Monte-Carlo
radial Program
53 statements
Source File
Uses:
iso_fortran_env
data_constants
data_input_prefixes
data_arguments
json_module
procedures_json_data_factory
procedures_errors
procedures_command_arguments
classes_periodic_box
procedures_boxes_factory
procedures_environment_inquirers
procedures_mixture_inquirers
procedures_complete_coordinates_reader
procedures_plmc_iterations
classes_radial_explorer
procedures_radial_explorer_factory
procedures_plmc_help
Calls
Variables
periodic_boxes max_box_size box_size radial_explorer num_components num_snaps i_snap snap_filename generating_data exploring_data
Variables
Type Attributes Name Initial
class(Abstract_Periodic_Box), allocatable :: periodic_boxes(:)
real(kind=DP), dimension(num_dimensions) :: max_box_size
real(kind=DP), dimension(num_dimensions) :: box_size
class(Abstract_Radial_Explorer), allocatable :: radial_explorer
integer :: num_components
integer :: num_snaps
integer :: i_snap
character(len=:), allocatable :: snap_filename
type(json_file) :: generating_data
type(json_file) :: exploring_data
All Programs
density plmc_explore plmc_generate radial
Call graph
radial calls complete_coordinates_read, boxes_create, plmc_set_num_snaps, warning_continue, json_data_destroy, plmc_catch_radial_help, property_num_components, radial_explorer_create, periodicity_is_xyz, boxes_destroy, radial_explorer_destroy, json_data_create, create_filename_from_argument
plmc_set_num_snaps calls write_coordinates, error_exit
plmc_catch_radial_help calls plmc_catch_help_core
create_filename_from_argument calls error_exit, check_positive, check_file_exists
write_coordinates calls write_coordinates_from_json
write_coordinates_from_json calls logical_from_json
logical_from_json calls check_data_found
check_data_found calls error_exit
plmc_catch_help_core calls error_exit
check_positive calls check_positive_integer_array, check_positive_real_scalar, check_positive_real_array, check_positive_integer_scalar
check_file_exists calls error_exit
check_positive_integer_array calls check_positive_integer_scalar
check_positive_real_scalar calls warning_continue, error_exit
check_positive_real_array calls check_positive_real_scalar
check_positive_integer_scalar calls warning_continue, error_exit