if (${CMAKE_Fortran_COMPILER_ID} MATCHES "GNU")
    find_program(GCC_AR gcc-ar)
    if(GCC_AR)
        set(CMAKE_AR "${GCC_AR}")
    endif(GCC_AR)
    mark_as_advanced(GCC_AR)

    find_program(GOLD gold)
    if (GOLD)
        set(CMAKE_LINKER "${GOLD}")
    endif(GOLD)
    mark_as_advanced(GOLD)
elseif (${CMAKE_Fortran_COMPILER_ID} MATCHES "Intel")
    find_program(XIAR xiar)
    if(XIAR)
        set(CMAKE_AR "${XIAR}")
    endif(XIAR)
    mark_as_advanced(XIAR)

    find_program(XILD xild)
    if(XILD)
        set(CMAKE_LINKER "${XILD}")
    endif(XILD)
    mark_as_advanced(XILD)
endif (${CMAKE_Fortran_COMPILER_ID} MATCHES "GNU")
